version: "3.8"
services:
  banner-service-test:
    build:
      context: .
      dockerfile: Dockerfile-test
    env_file:
        - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"