version: "3.8"

services:

  db:
    container_name: postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  banner-service:
    container_name: banner-service
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped


volumes:
  pg-data: