app:
  name: 'banner-management-server'
  version: '1.0.0'

http:
  addr: 127.0.0.1:8080
  timeout: 4s
  idle_timeout: 30s
  shutdown_timeout: 3s

log:
  level: 'local'

#postgres:
#  url: 'postgres://postgres:postgres@localhost:5432/postgres'


