app:
  name: 'banner-management-server'
  version: '1.0.0'

http:
  addr: 0.0.0.0:8080
  timeout: 4s
  idle_timeout: 30s
  shutdown_timeout: 3s

log:
  level: 'local'

scheduler:
  interval: '3h'

cache:
  expiration: '5m'

#postgres:
#  url: 'postgres://postgres:postgres@localhost:5432/postgres'


